# Generated by Django 3.2.7 on 2021-09-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pontoturistico_atracoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='atracoes',
        ),
    ]
